name: dependency_injection
version: 0.1.6
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-dependency-injection
description: Spring style annotation driven dependency injection
dependencies:
  patch_mirrors: ">=0.0.1 <0.1.0"
  annotate: ">=0.0.1 <0.1.0"
  logging: ">=0.11.0 <0.12.0"
dev_dependencies:
  behave:
    git: git@github.com:matthewfranglen/dart-behave.git
  unittest: any
